[workspace]
members = ["src/ic_backend", "src/ic_backend_types"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
candid = "0.10"

serde = "1.0"
serde_bytes = "0.11"

ic_backend_types = { path = "src/ic_backend_types" }
