name: ic_backend tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        shell: bash
        run: rustup show

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          shared-key: "unit-tests"

      - name: Run unit tests
        run: ./scripts/unit-test.sh

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        shell: bash
        run: rustup show

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          shared-key: "build-wasm"

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "latest"

      - name: Run integration tests
        run: ./scripts/integration-test.sh
