name: ic_backend tests

# only run when a commit is pushed to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        shell: bash
        run: rustup show

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          shared-key: "build-wasm"

      - name: Run integration tests
        run: ./scripts/integration-test.sh
